name: publish

on:
  release:
    types: [published]

permissions: {}

jobs:
  move-major-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create or Update Major Version Tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fullVersion = process.env.GITHUB_REF_NAME;
            const majorVersion = fullVersion.split('.')[0];
            const tagName = fullVersion.includes('-') ? `${majorVersion}-${fullVersion.split('-')[1].split('.')[0]}` : majorVersion;

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: context.sha
            }).catch(async (error) => {
              if (error.status === 422) {
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${tagName}`,
                  sha: context.sha,
                  force: true
                });
              } else {
                throw error;
              }
            });
